<?php
/**
 * Hizkuntza kateen mapa; euskaraz eta ingelesez eskaintzen da UI osoa.
 * Eskalagarritasuna kontuan hartuta, hizkuntza gehiago erraz gehitu daitezke.
 */
return [
    'eu' => [
        'title' => 'Ikasleen Kudeaketa',
        'add_student' => 'Ikasle berria gehitu',
        'view_logs' => 'Logak ikusi',
        'edit' => 'Editatu',
        'delete' => 'Ezabatu',
        'search' => 'Bilatu',
        'pagination_prev' => 'Aurrekoa',
        'pagination_next' => 'Hurrengoa',
        'pagination_showing' => 'Erregistroak',
        'name' => 'Izena',
        'surname' => 'Abizena',
        'cycle' => 'Zikloa',
        'level' => 'Maila',
        'photo' => 'Argazkia',
        'actions' => 'Ekintzak',
        'save' => 'Gorde',
        'save_changes' => 'Aldaketak gorde',
        'cancel' => 'Utzi',
        'no_students' => 'Ez dago ikaslerik oraindik.',
        'confirm_delete' => 'Ziur al zaude ikasle hau ezabatu nahi duzula?',
        'success_add' => 'Ikaslea ondo gehitu da',
        'success_delete' => 'Ikaslea ezabatu da',
        'success_update' => 'Aldaketak gordeta',
        'error_generic' => 'Errorea gertatu da',
        'error_required' => 'Ezin da hutsik egon',
        'error_invalid_name' => 'Izen eta abizenek letrak soilik onartzen dituzte',
        'details' => 'Ikusi',
        'back' => 'Atzera',
        'language_label' => 'Hizkuntza',
        'search_placeholder' => 'Bilatu izenez...',
        'order_by' => 'Ordenatu',
        'sort_izena' => 'Izenaren arabera',
        'sort_zikloa' => 'Zikloaren arabera',
        'sort_maila' => 'Mailaren arabera',
        'current_photo' => 'Uneko argazkia',
        'upload_help' => 'Onartutako formatuak: jpg, jpeg, png, webp. Gehienez 2MB.',
        'logs_title' => 'Aplikazioaren logak',
        'logs_empty' => 'Ez dago log erregistrorik.',
        'log_details' => 'Xehetasunak',
    ],
    'en' => [
        'title' => 'Student Management',
        'add_student' => 'Add new student',
        'view_logs' => 'View logs',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'search' => 'Search',
        'pagination_prev' => 'Previous',
        'pagination_next' => 'Next',
        'pagination_showing' => 'Showing',
        'name' => 'First name',
        'surname' => 'Last name',
        'cycle' => 'Program',
        'level' => 'Level',
        'photo' => 'Photo',
        'actions' => 'Actions',
        'save' => 'Save',
        'save_changes' => 'Save changes',
        'cancel' => 'Cancel',
        'no_students' => 'No students found yet.',
        'confirm_delete' => 'Are you sure you want to delete this student?',
        'success_add' => 'Ikaslea ondo gehitu da',
        'success_delete' => 'Ikaslea ezabatu da',
        'success_update' => 'Aldaketak gordeta',
        'error_generic' => 'Errorea gertatu da',
        'error_required' => 'This field is required',
        'error_invalid_name' => 'Names may only include letters, spaces, apostrophes, or hyphens',
        'details' => 'View',
        'back' => 'Back',
        'language_label' => 'Language',
        'search_placeholder' => 'Search by name...',
        'order_by' => 'Order by',
        'sort_izena' => 'Name',
        'sort_zikloa' => 'Program',
        'sort_maila' => 'Level',
        'current_photo' => 'Current photo',
        'upload_help' => 'Allowed formats: jpg, jpeg, png, webp. Max size 2MB.',
        'logs_title' => 'Application logs',
        'logs_empty' => 'No log entries yet.',
        'log_details' => 'Details',
    ],
];
