CREATE DATABASE IF NOT EXISTS ikasleak_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ikasleak_db;

CREATE TABLE ikasleak (
    id INT AUTO_INCREMENT PRIMARY KEY,
    izena VARCHAR(100) NOT NULL,
    abizena VARCHAR(100) NOT NULL,
    zikloa VARCHAR(100) NOT NULL,
    maila VARCHAR(50) NOT NULL,
    argazkia VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
